version: '3.8'

services:
  python-app:
    build: .
    environment:
      - DISCORD_TOKEN=
      - WEATHER_API_KEY=
      - LATITUDE=
      - LONGITUDE=
      - STATUS_MESSAGE_FORMAT={weather_emoji} | {current_time}
    volumes:
      - .:/app
    restart: always
